import { BarChart3, PieChart as PieIcon } from "lucide-react";
import { useState } from "react";
import ToggleButton from "@mui/material/ToggleButton";
import ToggleButtonGroup from "@mui/material/ToggleButtonGroup";
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { ReportDto } from "../../shared/types";
import { Card, Empty, PageTitle } from "../components/ui";
import { useApi } from "../hooks";
import { formatSeconds } from "../lib/api";
import { todayInJapan } from "../lib/dates";

const colors = ["#6750a4", "#b3261e", "#006a6a", "#7d5260", "#625b71", "#386a20"];

export function ReportPage() {
  const [period, setPeriod] = useState<"day" | "week" | "month">("week");
  const report = useApi<ReportDto>(`/api/reports/${period}?date=${todayInJapan()}`, [period]);
  const labels = { day: "今日", week: "今週", month: "今月" };
  return <><PageTitle title="振り返り" eyebrow="時間の使い方"><ToggleButtonGroup value={period} exclusive size="small" color="primary" onChange={(_, value: "day" | "week" | "month" | null) => { if (value) setPeriod(value); }}>{(["day", "week", "month"] as const).map((item) => <ToggleButton key={item} value={item} sx={{ px: 2, fontWeight: 700 }}>{labels[item]}</ToggleButton>)}</ToggleButtonGroup></PageTitle><div className="mb-5 grid gap-4 sm:grid-cols-3"><Card><p className="text-xs font-bold text-muted">{labels[period]}の合計</p><p className="mt-2 text-3xl font-black text-brand">{formatSeconds(report.data?.totalSeconds)}</p><p className="mt-1 text-xs text-muted">{report.data?.from} 〜 {report.data?.to}</p></Card><Card><p className="text-xs font-bold text-muted">活動の数</p><p className="mt-2 text-3xl font-black">{report.data?.byActivity.length ?? 0}<span className="ml-1 text-base">個</span></p></Card><Card><p className="text-xs font-bold text-muted">記録の日数</p><p className="mt-2 text-3xl font-black">{report.data?.byDay.filter((item) => item.seconds > 0).length ?? 0}<span className="ml-1 text-base">日</span></p></Card></div><div className="grid gap-5 lg:grid-cols-2"><Card><div className="mb-4 flex items-center gap-2"><BarChart3 size={18} className="text-brand" /><h2 className="font-black">日ごとの時間</h2></div>{report.data?.byDay.length ? <ResponsiveContainer width="100%" height={260}><BarChart data={report.data.byDay}><XAxis dataKey="date" tickFormatter={(value: string) => value.slice(5)} tick={{ fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis tickFormatter={(value: number) => `${Math.round(value / 3600)}h`} tick={{ fontSize: 11 }} axisLine={false} tickLine={false} width={32} /><Tooltip formatter={(value) => formatSeconds(Number(value))} /><Bar dataKey="seconds" fill="#6750a4" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer> : <Empty>この期間の記録はありません。</Empty>}</Card><Card><div className="mb-4 flex items-center gap-2"><PieIcon size={18} className="text-brand" /><h2 className="font-black">活動別の割合</h2></div>{report.data?.byActivity.length ? <div className="grid items-center gap-3 sm:grid-cols-[1fr_1fr]"><ResponsiveContainer width="100%" height={220}><PieChart><Pie data={report.data.byActivity} dataKey="seconds" nameKey="name" innerRadius={55} outerRadius={85} paddingAngle={3}>{report.data.byActivity.map((item, index) => <Cell key={item.activityId} fill={colors[index % colors.length]} />)}</Pie><Tooltip formatter={(value) => formatSeconds(Number(value))} /></PieChart></ResponsiveContainer><div className="space-y-3">{report.data.byActivity.map((item, index) => <div key={item.activityId} className="flex items-center justify-between gap-3 text-sm"><span className="flex items-center gap-2"><i className="size-2.5 rounded-full" style={{ backgroundColor: colors[index % colors.length] }} />{item.name}</span><span className="font-bold">{item.percentage}%</span></div>)}</div></div> : <Empty>この期間の記録はありません。</Empty>}</Card></div></>;
}
